run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - govet
    - gosec
    - revive
    - staticcheck
    - unused
issues:
  exclude-rules:
    - text: "G104" # https://securego.io/docs/rules/g104
