name: Appsync
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: emmett08/appsync
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test ./features -v
      - run: |
          go build -o appsync .
          chmod +x appsync
      - run: ./appsync generate \
          --root ${{ secrets.CATALOG_PATH }} \
          --repos-file repos.yaml
          --token ${{ secrets.GITHUB_TOKEN }}
